name: manual deployment workflow
on: 
  push:
    
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: Install cowsay programm
          run: sudo apt-get install -y cowsay

        - name: Execute cowsay cmd command
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Upload dragon.txt file
          uses: actions/upload-artifact@v4
          with:
            name: dragon.txt file
            path: dragon.txt
    
    Test:
        runs-on: ubuntu-latest
        needs: Build
        steps:
        - name: Dowload dragon.txt
          uses: actions/download-artifact@v4
          with:
            name: dragon.txt file
        - name: Test file exists
          run: grep -i "dragon" dragon.txt

    Deploy:
        runs-on: ubuntu-latest
        needs: Test
        environment:
          name: Deployment Environment
        steps:
        - name: Dowload dragon.txt
          uses: actions/download-artifact@v4
          with:
            name: dragon.txt file
        - name: Read file
          run: cat dragon.txt
      
